version: 1.0.2.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: >-
    $version = '1.0.2'
	
    nuget restore src\Umbraco.RedirectManager.sln

    nuget pack NuGet\Umbraco.RedirectManager.nuspec -Version $version -p "commitid=$env:APPVEYOR_REPO_COMMIT;coreVersion=$version;releaseNotes=$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

    (Get-Content -path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj -Raw) -replace '%releaseNotes%',"$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"| Set-Content -Path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.0.2'
  version_prefix: '1.0.2'
  package_version: '1.0.2'
  assembly_version: '1.0.2'
  file_version: '1.0.2'
  informational_version: '1.0.2'
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
for:

-
 branches:
   only:
     - master

 deploy:
 - provider: NuGet
   api_key:
     secure: tas6g7o5bleaFS68B8r1Hip3nDutOGGFKZT9Gm8RETKeLioLSeB0eWSajhWAfLKf
   artifact: /.nupkg/