version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    nuget restore src\Umbraco.RedirectManager.sln

    nuget pack NuGet\Umbraco.RedirectManager.nuspec
build:
  verbosity: minimal
artifacts:
- path: src\Akismet.Umbraco8\bin\Release\Umbraco.RedirectManager.Core.*.nupkg
  name: NuGet
- path: Umbraco.RedirectManager.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: nVErxJrUI4AStPan9b32g0YBTGMkjtMrehnItai8OYFy8EQNhDFWZNk5VReqC/pB
  artifact: /Umbraco.RedirectManager\.(.*)\.nupkg/
