version: 1.0.0.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- ps: >-
    $version = '1.0.0'

    (Get-Content -path Umbraco.RedirectManager.csproj -Raw) -replace '<Version>(.*)</Version>',"<Version>$version</Version>"| Set-Content -Path Umbraco.RedirectManager.csproj

    dotnet restore

    (Get-Content -path Umbraco.RedirectManager.csproj -Raw) -replace '%releaseNotes%',"$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"| Set-Content -Path Umbraco.RedirectManager.csproj
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 configuration: Debug
  
 deploy:
 - provider: NuGet
   api_key:
     secure: VNM5wnGi0PuiIXenGuDxuF+KvS30kSDa97hCQHkEE2DZ2s8bJC40DPJol7kEUQaS
   artifact: /.nupkg/