version: 1.0.2.{build}
image: Visual Studio 2019
configuration: Debug
before_build:
- ps: >-
    nuget restore src\Umbraco.RedirectManager.sln

    nuget pack NuGet\Umbraco.RedirectManager.nuspec -suffix ci -Version $env:APPVEYOR_BUILD_VERSION -p "commitid=$env:APPVEYOR_REPO_COMMIT;coreVersion=$env:APPVEYOR_BUILD_VERSION-ci;releaseNotes=$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

    (Get-Content -path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj -Raw) -replace '%releaseNotes%',"$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"| Set-Content -Path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-ci'
  version_prefix: '{version}'
  package_version: '{version}-ci'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 configuration: Debug
  
 deploy:
   provider: NuGet
   server: https://nuget.pkg.github.com/ahwm/index.json
   artifact: /.nupkg/
   username: ahwm
   api_key:
     secure: MErt1yyJNwqUUvMN8A1Um+YGisjzNLB6F2ATZ8mmnX41DqIMn9E0TnY/tDbSoBkM