version: 1.1.1.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: >-
    $version = '1.1.1'

    (Get-Content -path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj -Raw) -replace '<Version>(.*)</Version>',"<Version>$version</Version>"| Set-Content -Path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj

    nuget pack NuGet\Umbraco.RedirectManager.nuspec -Version $version -p "commitid=$env:APPVEYOR_REPO_COMMIT;coreVersion=$version;releaseNotes=$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

    (Get-Content -path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj -Raw) -replace '%releaseNotes%',"$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"| Set-Content -Path src\Umbraco.RedirectManager\Umbraco.RedirectManager.csproj

    nuget restore src\Umbraco.RedirectManager.sln
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
for:

-
 branches:
   only:
     - master

 deploy:
 - provider: NuGet
   api_key:
     secure: W9SwSp8OTa2cGvMnxh1MBzOmzVLBjWy1slZ9QVy4wiBpioVB4uG8tYtkiT4Wk6Bk
   artifact: /.nupkg/
