version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    nuget restore src\Umbraco.RedirectManager.sln

    nuget pack NuGet\Umbraco.RedirectManager.nuspec
build:
  verbosity: minimal
artifacts:
- path: src\Umbraco.RedirectManager\bin\Release\RedirectManager.Umbraco8.Core.*.nupkg
  name: NuGet
- path: RedirectManager.Umbraco8.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: uGVgzA/BHFwpKi+XMdYXns9RBdqXTf2bb7hgS++qWLaAszaQm7cJOqPWhtziW4vJ
  artifact: /RedirectManager.Umbraco8\.(.*)\.nupkg/
